name: Check

env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: "emsdk-cache"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Cache TinyGo
        uses: actions/cache@v4
        with:
          path: tinygo_0.37.0_amd64.deb
          key: tinygo-0.37.0-${{ runner.os }}
      - name: Install TinyGo
        run: |
          if [ ! -f tinygo_0.37.0_amd64.deb ]; then
            wget https://github.com/tinygo-org/tinygo/releases/download/v0.37.0/tinygo_0.37.0_amd64.deb
          fi
          sudo dpkg -i tinygo_0.37.0_amd64.deb
          export PATH=$PATH:/usr/local/bin
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown, wasm32-wasip1
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: 0.13.1
      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: ./.githooks/pre-push
